"""add timestamps to users and rulesets, unique constraint on user_overlays

Revision ID: 2072048c5919
Revises: bf40d8ad6a37
Create Date: 2026-02-11 00:27:27.482761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2072048c5919'
down_revision = 'bf40d8ad6a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rulesets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user_overlays', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_overlay_entity', ['user_id', 'ruleset_id', 'entity_type', 'source_key', 'campaign_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user_overlays', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_overlay_entity', type_='unique')

    with op.batch_alter_table('rulesets', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
