"""Initial tables

Revision ID: bf40d8ad6a37
Revises: 
Create Date: 2026-01-30 01:53:11.126363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf40d8ad6a37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rulesets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_config', sa.Text(), nullable=True),
    sa.Column('entity_types', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('ruleset_id', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ruleset_entities',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('ruleset_id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('source_key', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('entity_data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruleset_id', 'entity_type', 'source_key', name='uq_ruleset_entity')
    )
    with op.batch_alter_table('ruleset_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ruleset_entities_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruleset_entities_name'), ['name'], unique=False)

    op.create_table('characters',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('character_type', sa.String(length=10), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('core_data', sa.Text(), nullable=True),
    sa.Column('class_data', sa.Text(), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('spells', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_overlays',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('ruleset_id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('source_key', sa.String(length=200), nullable=False),
    sa.Column('overlay_type', sa.String(length=20), nullable=False),
    sa.Column('overlay_data', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_overlays')
    op.drop_table('characters')
    with op.batch_alter_table('ruleset_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ruleset_entities_name'))
        batch_op.drop_index(batch_op.f('ix_ruleset_entities_entity_type'))

    op.drop_table('ruleset_entities')
    op.drop_table('campaigns')
    op.drop_table('users')
    op.drop_table('rulesets')
    # ### end Alembic commands ###
